### ISSUE TITLE
Stacks

### ISSUE THREAD

**Issue by diegobrum** [argilando/365-dias-de-agir#5]
### Goal

As a Project Manager, I want to know about key stacks, so all stackholders can undestand the same thing and I can create technical stories and tasks
### Acceptance criteria

A doc called **_Stacks-pt_br.md_** inside **_docs/_** folder with these informations:
1. Server
   > Stacks used in web.api
2. Client
   > Stacks used in web.app

**Comment by diegobrum** [comment]
Options to use:
* Server
    * NodeJs w/ express framework
    * Python
    * C# w/ CoreClr
    * Go language

* Client
    * Pure Bootstrap
    * Angular2
    * React

**Comment by borgotecnologia** [comment]
I'd rather goLang or python for server side and Angular 2 or bootstrap to client side. 
What's your preference?

**Comment by diegobrum** [comment]
Angular2 and GoLang
Go, go, go?

**Comment by diegobrum** [comment]
@borgotecnologia Please, review

**Comment by borgotecnologia** [comment]
Document ok!
